<?php


return [

    "SUCCESS_CODE"=>100,

    'DEFAULT_PAGINATE_LIMIT'=>10,
    'ADMIN_EMAIL'=>'imrancse94@gmail.com',

    'VALIDATION_ERROR'=>1000,
    'UNATHENTICATED_ERROR'=>4001,
    
    'LOGIN_FAILED'=>"E105",
    'LOGIN_SUCCESS'=>"105",
    
    'USER_SIGNUP_FAILED'=>"E106",
    'USER_SIGNUP_SUCCESS'=>"106",

    'AUTH_USER_SUCCESS'=>112,

    'SUBJECT_CREATE_SUCCESS'=>"113",
    'SUBJECT_CREATE_FAILED'=>"E113",

];